### PR TITLE
Incompletely btrace output before application exit

### PR DESCRIPTION
**Pull request by mfilser**
Hello @jbachorik,
here are 2 small Bugfixes.
* Commit a93afde7f96b21ab006749d741139f7a8b880531 fixes a Bug of Issue #93
* Commit 3e56b6b8578d09eedd072f8aa857958d4b4d06d8 fixes a Bug which i reported in Issue #136 and works for me.
Maybe you want to review the 2 commits and merge it into your master branch?

Bests regards,
Martin

### CODE REVIEW

**Comment by mfilser** [comment]
Hello @jbachorik,
the branch is now finished. What do you think about the commits?

**Comment by jbachorik** [comment]
I think you can merge [a93afde](https://github.com/mfilser/btrace/commit/a93afde7f96b21ab006749d741139f7a8b880531) and [3e56b6b](https://github.com/mfilser/btrace/commit/3e56b6b8578d09eedd072f8aa857958d4b4d06d8)

Add a shutdown hook for the __com.sun.btrace.agent.Client__ - you can access the associated BTraceRuntime instance from there to call 'handleExit()' and use an overridable protected method to allow the FileClient to flush its output stream before exiting the process.

And you still can remove the shutdown hook handling from __com.sun.btrace.agent.Main__

**Comment by mfilser** [comment]
So i should change the commits?
I think it doesn't matter if the shutdown hook is also present, but if the hook is present, it's always sure that the thread ends normally ...

**Comment by jbachorik** [comment]
Yes, I would prefer having it simplified.
If you keep multiple shutdown hooks it will make it much harder to maintain and eg. you would be calling rt.handleExit() twice for each socket connected client.

**Comment by mfilser** [comment]
Ok. I try it tomorrow

**Comment by jbachorik** [comment]
Thanks!

**Comment by mfilser** [comment]
Done. The fix works as expected on my computer.

**Comment by jbachorik** [comment]
Fix integrated.

Martin, thanks for contributing!

**Pull request merged**
