### PR TITLE
Btrace output beautified

### PR DESCRIPTION
**Pull request by mfilser**
Hello @jbachorik,
here are a few commits to beautify the output of GridDataCommand#print(PrintWriter).
I use Java8 here and hope that the changes to use Java8 in btrace are ok. I dont't know if there are other things to change to use Java8 in btrace.
Maybe you want to review the commit and let me know what you think about it?

### CODE REVIEW

**Comment by jbachorik** [comment]
First of all - thanks for contributing!

We need to support JDK 7 in BTrace. Therefore we are not using any JDK 8 lang constructs. I think you can adapt the patch to support JDK 7 quite easily.

Also, this pull request seems to be intermingled with the changes for your other pull request #146 - this might make it unnecessary complicated when merging.

And, at the end - before accepting any pull requests I need you to read, understand and sign the [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html).

**Comment by mfilser** [comment]
Hello jbachorik,
i will change the code to support JDK7 and rebase it to current master branch without commits of #146.

One question about the Oracle Contributor Agreement. I have looked the list, but i can't find your name on it. So why is it necessary to sign the OCA? What disadvantage do i have when i sign it?

**Comment by jbachorik** [comment]
Regarding OCA - I am an Oracle employee and therefore all my contributions
are considered as covered by OCA.

Shortly - by signing OCA you are basically transferring the rights to your
contributions to Oracle. Oracle, in turn, will give you the legal
protection in all the copyright/patent issues regarding your contributions.
I would recommend reading the OCA thoroughly before signing so you are sure
you agree with the implications.

**Comment by mfilser** [comment]
Is the OCA in German available?

**Comment by jbachorik** [comment]
I don't think there would be any other OCA version than english :(

**Comment by mfilser** [comment]
Oca signed. As soon as i have the changes i will write here.

**Comment by mfilser** [comment]
Hello @jbachorik,
the branch is now finished. What do you think about the commits?

**Comment by mfilser** [comment]
Is there a coding style available for the btrace project?
Or the best would be to have a checkstyle.xml for the coding style. Maybe you have something like that?

**Comment by jbachorik** [comment]
No specific coding style - we were following the code conventions used in
OpenJDK development. Unfortunately, the document is not available anymore.

The checkstyle.xml sounds as a good idea to implement (although not readily
available, too).

**Comment by mfilser** [comment]
Done. Why does sometimes the test
```
com.sun.btrace.BTraceFunctionalTests > testOSMBean FAILED
    java.lang.AssertionError at BTraceFunctionalTests.java:58
```

fail on travis-ci.org?

I did again a push after a git commit --amend and then the tests is completed without errors...

**Comment by jbachorik** [comment]
There might be race when running the external JVM test app and attaching to
it. Can't reproduce it locally, though :(

**Comment by jbachorik** [comment]
Branch integrated.

Martin, thanks a lot for contributing!

**Pull request merged**
