### PR TITLE
Support JDK 1.7+ on OS X

### PR DESCRIPTION
**Pull request by oschrenk**
JDK versions starting with 1.7 are installed to

```
/Library/Java/JavaVirtualMachines/<version>/Contents/Home
```

### CODE REVIEW

**Comment by jbachorik** [comment]
Hi Oliver,

thanks for the fix. But you will need to sign the [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) before I am able to accept this pull request. Sorry for the inconvenience.

-JB-

**Comment by oschrenk** [comment]
Working on it. Just wanted to send the pull request to get some feedback. 

It would be nice if the page would actually explain the steps you have to do. I have to go to the FAQ to actually figure it out on my own.

**Comment by oschrenk** [comment]
Mail sent.

**Comment by jbachorik** [comment]
OCA has been successfully processed :) Congrats!

**Pull request merged**
