### PR TITLE
Mac OS X support JDK1.7+

### PR DESCRIPTION
**Pull request by liuxinglanyue**

### CODE REVIEW

**Comment by jbachorik** [comment]
Thanks for the contribution!

Please, sign [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) before this pull request may be accepted.

**Comment by liuxinglanyue** [comment]
ok

**Comment by jbachorik** [comment]
Just out of curiosity - did you sign the OCA?

**Comment by jbachorik** [comment]
Ping. Will you be signing the OCA? It would be shame to let this contribution waste. If I don't hear you in a weak I will be forced to close this pull request :(

**Pull request closed without merging**
